### ISSUE TITLE
Node.js 16 actions are deprecated.

### ISSUE THREAD

**Issue by Jarod42** [joncloud/nsis-action#34]
using

```
    - name: Create nsis installer
      uses: joncloud/makensis-action@v4
```

We got github warning:

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: joncloud/makensis-action@v4. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by joncloud** [comment]
@Jarod42 thanks for the heads up. I've upgraded this action to run on Node.js 20.

**Comment by Jarod42** [comment]
Confirmed that `uses: joncloud/makensis-action@v4.1` doesn't produce the warning :-)
